name: Check Tests

on: [push, pull_request]


jobs:
  build:

    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: check pass file
      run: | 
        echo "Testing Pass condition"
        if [[ $(cat $(git rev-parse --show-toplevel)/src/tests/test-testP-results.txt) == "pass" ]]; exit 0 ; fi
    - name: check fail file
      run:
        echo "Testing Fail condition"
        if [[ $(cat $(git rev-parse --show-toplevel)/src/tests/test-testF-results.txt) == "fail" ]]; exit 1 ; fi
